# Generated by Django 3.1.2 on 2020-10-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.TextField(blank=True)),
                ('recipient', models.EmailField(max_length=200, verbose_name='email')),
            ],
        ),
    ]
