# Generated by Django 3.1.2 on 2020-10-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mails',
            name='defer',
            field=models.SmallIntegerField(blank=True, default=0, verbose_name='defer'),
        ),
        migrations.AddField(
            model_name='mails',
            name='send_date',
            field=models.DateTimeField(blank=True, default=None, verbose_name='send_date'),
        ),
        migrations.AddField(
            model_name='mails',
            name='status',
            field=models.BooleanField(default=False, verbose_name='sended'),
        ),
    ]
